### ISSUE TITLE
Servers not being added to main window

### ISSUE THREAD

**Issue by mpschorr** [MrEnxo/minetron#10]
**Current Behavior:** After logging in, no servers show in the main window.
**Steps to reproduce:**
`git clone https://github.com/MrEnxo/minetron`
`cd minetron`
`npm start`
`(Log in to minehut)`

**Example:** https://i.imgur.com/QmzLUHJ.png

No errors are being thrown in the console.

**Comment by mygizli04** [comment]
Hi, thanks for opening an issue. Looks like i made a typo somewhere.. I'll be making a fix in a minute

**Comment by mygizli04** [comment]
[Fixed](https://github.com/MrEnxo/minetron/commit/0bf81fc60dda9849ae8b9b6050a574b8aeb4e824).

Could you please `git pull` and try again?

**Comment by mpschorr** [comment]
That fixed it.
